language: ruby
rvm:
- 2.5.1
script:
- bundle exec rails db:migrate
- bundle exec rspec -fd spec
deploy:
  provider: heroku
  api_key:
    secure: eBPNcE3UVbDJLzI+AAjVvU6IuKdS4MRtEmrSvDDIL6Xd5SB9a8GzgKsufBnTtFqaZ63UZYhfM5ZKm1MQwe9QxnQI+kmATXW0f/sGESBpXzRDl3nx3+Da+AnUB0Dqpnde/xBpHxKfrhohkyDC01DkHEtHlZvpJj5v5QJgLlY+X2vDParqgmuNSYD2orO7c7g0BW9cBXnK/JuX+DNS1gDuCMg4wTP+mORgVczqnlnR4Bq/NSqNbgHf42N3GzqJQWnzGjUzJThbSkkuc6csKQk7PqJyMXkSFKp59JzV+TaxF+6+sJTNGF2LY8S/ZbMm5YfdGxImQZexGBOPujKnKa/5vP0wjkYp0tjn9Z49iG2fMvmYYP08OegylbzLPWZcSVsUZ1wVVfxIcwTdi+XpIF6dUR43k9rNBGTz16G8KwgEhUS3v0+IGisLoFi4xt/GGEcA35JcvqliHUB8Nvcr2Mc8RBRoDZkeik8/eGFLs/B2sggtPOknyQIUeqKV50mlvf44rC5bLXY1Nh6FykLR1FEmfvRADfj/GoVRiadEGPIX8d6QnL1NC8DiG7e9Vs2Lmz1na9N4Hw8SiC/3CIuMh5MhVJZxPP+GaZTzNzL2xFhyJlWF/umr5qSSK2l5ZL/6Rl2oIHeq8TbvCA/r0fQDSVucxDzH7vn7upkpF4mTG74l650=
  app: fierce-thicket-13416
  on:
    repo: mevid93/WPORatebeer
